# Generated by Django 6.0.7 on 2026-08-26 19:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avaliação comercial de 0 a 5.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
    ]
