# Generated by Django 6.0.7 on 2026-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_categorias_gf_cronograma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicaambiente',
            options={'ordering': ('nome',), 'verbose_name': 'Característica de ambiente', 'verbose_name_plural': 'Características de ambientes'},
        ),
        migrations.AlterModelOptions(
            name='categoriagrandefornecedor',
            options={'ordering': ('ordem', 'nome'), 'verbose_name': 'Categoria de Grande Fornecedor', 'verbose_name_plural': 'Categorias de Grandes Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='opcaoespecificacaograndefornecedor',
            options={'ordering': ('categoria__ordem', 'ordem', 'nome'), 'verbose_name': 'Opção de especificação GF', 'verbose_name_plural': 'Opções de especificação GF'},
        ),
        migrations.AlterModelOptions(
            name='tipoambiente',
            options={'ordering': ('nome',), 'verbose_name': 'Tipo de ambiente', 'verbose_name_plural': 'Tipos de ambientes'},
        ),
        migrations.AlterModelOptions(
            name='tipoitemgrandefornecedor',
            options={'ordering': ('categoria__ordem', 'ordem', 'nome'), 'verbose_name': 'Tipo de item de Grande Fornecedor', 'verbose_name_plural': 'Tipos de itens de Grandes Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='tipopavimento',
            options={'ordering': ('ordem', 'nome'), 'verbose_name': 'Tipo de pavimento', 'verbose_name_plural': 'Tipos de pavimento'},
        ),
    ]
