# Generated by Django 6.0.7 on 2026-07-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integracoes', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Código')),
                ('estrutural', models.BooleanField(default=False, help_text='Marque para linhas como RESUMO, RESUMO GERAL e MARCOS.', verbose_name='Disciplina estrutural')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['estrutural', 'ativa'], name='planej_disc_estrut_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtividadeCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto_original', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Nome original do projeto')),
                ('tipo_empreendimento', models.CharField(blank=True, max_length=80, verbose_name='Prédio ou casa')),
                ('quantidade_unidades', models.PositiveIntegerField(default=1, verbose_name='Quantidade de unidades')),
                ('semana', models.PositiveIntegerField(db_index=True, verbose_name='Semana')),
                ('data_atualizacao', models.DateField(db_index=True, verbose_name='Data de atualização')),
                ('local_tarefa', models.CharField(blank=True, max_length=255, verbose_name='Local da tarefa')),
                ('nome_tarefa', models.CharField(max_length=500, verbose_name='Nome da tarefa')),
                ('inicio_real', models.DateField(blank=True, null=True, verbose_name='Início real')),
                ('duracao_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duração real')),
                ('termino_real', models.DateField(blank=True, null=True, verbose_name='Término real')),
                ('inicio_base', models.DateField(blank=True, null=True, verbose_name='Início base')),
                ('duracao_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duração base')),
                ('termino_base', models.DateField(blank=True, null=True, verbose_name='Término base')),
                ('percentual_concluida', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% concluída')),
                ('percentual_previsto_tarefa', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% previsto da tarefa')),
                ('checklist_habitese', models.CharField(blank=True, max_length=255, verbose_name='Checklist Habite-se')),
                ('checklist_cef', models.CharField(blank=True, max_length=255, verbose_name='Checklist CEF')),
                ('responsavel', models.CharField(blank=True, max_length=255, verbose_name='Responsável')),
                ('peso', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Peso')),
                ('percentual_executado', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% executado')),
                ('percentual_previsto', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% previsto')),
                ('inicio_semana', models.DateField(blank=True, null=True, verbose_name='Início da semana')),
                ('semana_anterior', models.IntegerField(blank=True, null=True, verbose_name='Semana anterior')),
                ('semana_seguinte', models.IntegerField(blank=True, null=True, verbose_name='Semana seguinte')),
                ('linha_origem', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Linha de origem')),
                ('dados_originais', models.JSONField(blank=True, default=dict, verbose_name='Dados originais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_cronograma', to='obras.obra', verbose_name='Obra')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='planejamento.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Atividade do cronograma',
                'verbose_name_plural': 'Atividades do cronograma',
                'ordering': ['obra', 'semana', 'disciplina', 'nome_tarefa'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('semana_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana inicial')),
                ('semana_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana final')),
                ('total_atividades', models.PositiveBigIntegerField(default=0, verbose_name='Total de atividades')),
                ('ativa', models.BooleanField(default=False, verbose_name='Importação ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('importacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_obra', to='integracoes.importacao', verbose_name='Importação')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_cronograma', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Importação de cronograma',
                'verbose_name_plural': 'Importações de cronograma',
                'ordering': ['-data_referencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HABITESE', 'Habite-se'), ('CEF', 'CEF'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('semana', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana')),
                ('valor_original', models.CharField(blank=True, max_length=255, verbose_name='Valor original')),
                ('percentual_concluido', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% concluído')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atividade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_gerados', to='planejamento.atividadecronograma', verbose_name='Atividade de origem')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_cronograma', to='obras.obra', verbose_name='Obra')),
                ('importacao_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='planejamento.importacaocronograma', verbose_name='Importação do cronograma')),
            ],
            options={
                'verbose_name': 'Checklist do cronograma',
                'verbose_name_plural': 'Checklists do cronograma',
                'ordering': ['obra', 'tipo', 'semana', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='atividadecronograma',
            name='importacao_cronograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='planejamento.importacaocronograma', verbose_name='Importação do cronograma'),
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('semana', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data prevista')),
                ('data_realizada', models.DateField(blank=True, null=True, verbose_name='Data realizada')),
                ('percentual_concluido', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% concluído')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atividade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcos_gerados', to='planejamento.atividadecronograma', verbose_name='Atividade de origem')),
                ('importacao_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='planejamento.importacaocronograma', verbose_name='Importação do cronograma')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcos', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Marco',
                'verbose_name_plural': 'Marcos',
                'ordering': ['obra', 'data_prevista', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='importacaocronograma',
            index=models.Index(fields=['obra', 'ativa'], name='planej_import_obra_ativa_idx'),
        ),
        migrations.AddIndex(
            model_name='importacaocronograma',
            index=models.Index(fields=['data_referencia'], name='planej_import_data_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistcronograma',
            index=models.Index(fields=['obra', 'tipo'], name='planej_check_obra_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistcronograma',
            index=models.Index(fields=['obra', 'concluido'], name='planej_check_obra_conc_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadecronograma',
            index=models.Index(fields=['importacao_cronograma', 'obra'], name='planej_ativ_import_obra_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadecronograma',
            index=models.Index(fields=['obra', 'semana'], name='planej_ativ_obra_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadecronograma',
            index=models.Index(fields=['obra', 'data_atualizacao'], name='planej_ativ_obra_data_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadecronograma',
            index=models.Index(fields=['disciplina', 'semana'], name='planej_ativ_disc_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='marco',
            index=models.Index(fields=['obra', 'concluido'], name='planej_marco_obra_conc_idx'),
        ),
        migrations.AddIndex(
            model_name='marco',
            index=models.Index(fields=['obra', 'data_prevista'], name='planej_marco_obra_data_idx'),
        ),
    ]
