# Generated by Django 6.0.7 on 2026-07-28 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(db_index=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('quantidade_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('semana', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data_atualizacao', models.DateField(blank=True, db_index=True, null=True)),
                ('local_tarefa', models.TextField(blank=True)),
                ('nome_tarefa', models.TextField(blank=True)),
                ('inicio_real', models.DateField(blank=True, null=True)),
                ('duracao_real', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('termino_real', models.DateField(blank=True, null=True)),
                ('inicio_base', models.DateField(blank=True, null=True)),
                ('duracao_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('termino_base', models.DateField(blank=True, null=True)),
                ('percentual_concluida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('percentual_previsto_tarefa', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('disciplina', models.CharField(blank=True, db_index=True, max_length=255)),
                ('checklist_habitese', models.CharField(blank=True, max_length=255)),
                ('checklist_cef', models.CharField(blank=True, max_length=255)),
                ('responsavel', models.CharField(blank=True, db_index=True, max_length=255)),
                ('peso', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('percentual_executado', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('percentual_previsto', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('inicio_semana', models.DateField(blank=True, null=True)),
                ('semana_anterior', models.CharField(blank=True, max_length=100)),
                ('semana_seguinte', models.CharField(blank=True, max_length=100)),
                ('inicio_semana_base', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de cronograma',
                'verbose_name_plural': 'Registros de cronograma',
                'ordering': ('projeto', 'semana', 'id'),
            },
        ),
        migrations.RemoveIndex(
            model_name='atividadecronograma',
            name='planej_ativ_import_obra_idx',
        ),
        migrations.RemoveIndex(
            model_name='atividadecronograma',
            name='planej_ativ_obra_sem_idx',
        ),
        migrations.RemoveIndex(
            model_name='atividadecronograma',
            name='planej_ativ_obra_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='atividadecronograma',
            name='planej_ativ_disc_sem_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklistcronograma',
            name='planej_check_obra_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklistcronograma',
            name='planej_check_obra_conc_idx',
        ),
        migrations.RemoveIndex(
            model_name='disciplina',
            name='planej_disc_estrut_idx',
        ),
        migrations.RemoveIndex(
            model_name='marco',
            name='planej_marco_obra_conc_idx',
        ),
        migrations.RemoveIndex(
            model_name='marco',
            name='planej_marco_obra_data_idx',
        ),
        migrations.AlterModelOptions(
            name='importacaocronograma',
            options={'ordering': ('-criado_em',), 'verbose_name': 'Importação de cronograma', 'verbose_name_plural': 'Importações de cronograma'},
        ),
        migrations.RemoveIndex(
            model_name='importacaocronograma',
            name='planej_import_obra_ativa_idx',
        ),
        migrations.RemoveIndex(
            model_name='importacaocronograma',
            name='planej_import_data_idx',
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='arquivo_drive_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='data_modificacao_drive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='erro_detalhado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='executado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_cronograma_planejamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='finalizou_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='hash_arquivo',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='iniciou_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='linhas_importadas',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='nome_arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='projetos_identificados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='semanas_identificadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='status',
            field=models.CharField(choices=[('PROCESSANDO', 'Processando'), ('VALIDANDO', 'Validando'), ('CONCLUIDA', 'Concluída'), ('FALHOU', 'Falhou')], db_index=True, default='PROCESSANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='tamanho_arquivo_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacaocronograma',
            name='total_linhas_arquivo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importacaocronograma',
            name='ativa',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='importacaocronograma',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='importacaocronograma',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='importacaocronograma',
            index=models.Index(fields=['ativa', 'status'], name='planejament_ativa_8e1d86_idx'),
        ),
        migrations.AddIndex(
            model_name='importacaocronograma',
            index=models.Index(fields=['hash_arquivo'], name='planejament_hash_ar_7d9c07_idx'),
        ),
        migrations.AddIndex(
            model_name='importacaocronograma',
            index=models.Index(fields=['data_modificacao_drive'], name='planejament_data_mo_bcff2e_idx'),
        ),
        migrations.AddField(
            model_name='registrocronograma',
            name='importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='planejamento.importacaocronograma'),
        ),
        migrations.RemoveField(
            model_name='atividadecronograma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='atividadecronograma',
            name='importacao_cronograma',
        ),
        migrations.RemoveField(
            model_name='atividadecronograma',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='checklistcronograma',
            name='atividade_origem',
        ),
        migrations.RemoveField(
            model_name='checklistcronograma',
            name='importacao_cronograma',
        ),
        migrations.RemoveField(
            model_name='checklistcronograma',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='marco',
            name='atividade_origem',
        ),
        migrations.RemoveField(
            model_name='marco',
            name='importacao_cronograma',
        ),
        migrations.RemoveField(
            model_name='marco',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='data_referencia',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='importacao',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='semana_final',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='semana_inicial',
        ),
        migrations.RemoveField(
            model_name='importacaocronograma',
            name='total_atividades',
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['importacao', 'projeto', 'semana'], name='planejament_importa_709cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['importacao', 'disciplina'], name='planejament_importa_4a1eed_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['importacao', 'data_atualizacao'], name='planejament_importa_051ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['projeto', 'responsavel'], name='planejament_projeto_61aa72_idx'),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='ChecklistCronograma',
        ),
        migrations.DeleteModel(
            name='AtividadeCronograma',
        ),
        migrations.DeleteModel(
            name='Marco',
        ),
    ]
