# Generated by Django 6.0.7 on 2026-07-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0002_registrocronograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocronograma',
            name='chave_atividade',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='registrocronograma',
            name='inicio_base_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrocronograma',
            name='reprogramada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='registrocronograma',
            name='reprogramada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrocronograma',
            name='termino_base_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['importacao', 'chave_atividade'], name='plan_imp_chave_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocronograma',
            index=models.Index(fields=['importacao', 'reprogramada'], name='plan_imp_reprog_idx'),
        ),
    ]
