# Generated by Django 6.0.7 on 2026-08-07 17:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0004_atividadeplanejamento_vinculo_obra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoPlanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
                ('unidade_padrao', models.CharField(blank=True, choices=[('UN', 'Unidade'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('M3', 'Metro cúbico'), ('KG', 'Quilograma'), ('T', 'Tonelada'), ('L', 'Litro'), ('SC', 'Saco'), ('CX', 'Caixa'), ('PC', 'Peça'), ('GL', 'Galão'), ('RL', 'Rolo'), ('PT', 'Pacote'), ('VB', 'Verba')], max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_planejamento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insumo de planejamento',
                'verbose_name_plural': 'Insumos de planejamento',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='SuprimentoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('M3', 'Metro cúbico'), ('KG', 'Quilograma'), ('T', 'Tonelada'), ('L', 'Litro'), ('SC', 'Saco'), ('CX', 'Caixa'), ('PC', 'Peça'), ('GL', 'Galão'), ('RL', 'Rolo'), ('PT', 'Pacote'), ('VB', 'Verba')], max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_limite_compra', models.DateField(blank=True, db_index=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suprimentos', to='planejamento.atividadeplanejamento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suprimentos_atividade_criados', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suprimentos_atividades', to='planejamento.insumoplanejamento')),
            ],
            options={
                'verbose_name': 'Suprimento de atividade',
                'verbose_name_plural': 'Suprimentos de atividades',
                'ordering': ('atividade_id', 'data_limite_compra', 'insumo__nome', 'id'),
                'indexes': [models.Index(fields=['atividade', 'ativo'], name='plan_sup_ativ_ativo_idx'), models.Index(fields=['atividade', 'data_limite_compra'], name='plan_sup_ativ_data_idx'), models.Index(fields=['insumo', 'ativo'], name='plan_sup_ins_ativo_idx')],
            },
        ),
    ]
