from .menu import menu_suprimentos
from .processos import (
    dashboard,
    detalhe_processo,
    lista_pedidos,
    lista_processos,
    novo_processo,
    pdf_solicitacao_aprovada,
    pdf_solicitacao_cotacao,
)
from .acoes import (
    acao_adjudicar,
    acao_analise_tecnica_lote,
    acao_aprovar_toda_compatibilizacao,
    acao_aprovar,
    acao_cancelar_adjudicacao,
    acao_compatibilizar,
    acao_concluir_compatibilizacao,
    acao_concluir_negociacao,
    acao_enviar_solicitacao_fornecedor,
    acao_marcar_solicitacao_enviada,
    acao_decisao_comercial_lote,
    acao_excluir_cotacao,
    acao_enviar_cotacao_compatibilizacao,
    acao_enviar_cotacao_aprovacao,
    acao_devolver_cotacao_negociacao,
    acao_retornar_etapa,
    acao_anexar_documento,
    acao_gerar_pedidos,
    acao_incluir_cotacao,
    acao_incluir_item_cotacao,
    acao_incluir_necessidade,
    acao_negociar,
    acao_salvar_proposta_completa,
    acao_anexar_arquivo_pedido,
    acao_atualizar_status_pedido,
    acao_atualizar_previsao_pedido,
    acao_receber_pedido,
    acao_cancelar_pedido,
)

__all__ = [name for name in globals() if not name.startswith("_")]
