# Generated by Django 6.0.7 on 2026-07-21 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('GERENCIA', 'Gerência'), ('ENGENHARIA', 'Engenharia'), ('PLANEJAMENTO', 'Planejamento'), ('SUPRIMENTOS', 'Suprimentos'), ('COMPRAS', 'Compras'), ('FINANCEIRO', 'Financeiro'), ('ALMOXARIFADO', 'Almoxarifado'), ('PROJETOS', 'Projetos'), ('POS_OBRA', 'Pós-obra'), ('ADMINISTRATIVO', 'Administrativo'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30, verbose_name='Cargo/setor')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/perfis/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Perfil ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_erp', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de usuário',
                'verbose_name_plural': 'Perfis de usuários',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('OBRAS', 'Obras'), ('PLANEJAMENTO', 'Planejamento'), ('SUPRIMENTOS', 'Suprimentos'), ('COMPRAS', 'Compras'), ('CONTRATOS', 'Contratos'), ('FINANCEIRO', 'Financeiro'), ('ALMOXARIFADO', 'Almoxarifado'), ('PROJETOS', 'Projetos'), ('VISTORIAS', 'Vistorias'), ('DIARIO_OBRA', 'Diário de obra'), ('POS_OBRA', 'Pós-obra'), ('RELATORIOS', 'Relatórios'), ('INTEGRACOES', 'Integrações'), ('USUARIOS', 'Usuários e permissões')], max_length=30, verbose_name='Módulo')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Somente leitura'), ('EDICAO', 'Leitura e edição'), ('APROVACAO', 'Leitura, edição e aprovação'), ('ADMINISTRADOR', 'Administrador do módulo')], default='LEITURA', max_length=20, verbose_name='Nível de permissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Permissão ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos_erp', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de módulo',
                'verbose_name_plural': 'Permissões de módulos',
                'ordering': ['usuario__username', 'modulo'],
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='usr_perm_usu_ativo_idx'), models.Index(fields=['modulo', 'nivel'], name='usr_perm_mod_niv_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo'), name='usr_perm_usu_mod_uniq')],
            },
        ),
    ]
