from django.urls import path
from compras import views

app_name = "compras"

urlpatterns = [
    path("arquivos/cotacoes/<int:pk>/", views.baixar_documento_cotacao, name="baixar_documento_cotacao"),
    path("arquivos/contratacoes/<int:pk>/", views.baixar_documento_contratacao, name="baixar_documento_contratacao"),
    path("arquivos/pedidos/<int:pk>/", views.baixar_anexo_pedido, name="baixar_anexo_pedido"),
    path("arquivos/notas-fiscais/<int:pk>/", views.baixar_nota_fiscal_recebimento, name="baixar_nota_fiscal_recebimento"),
    path("", views.menu_suprimentos, name="menu"),
    path("painel/", views.dashboard, name="dashboard"),
    path("processos/", views.lista_processos, name="lista_processos"),
    path("processos/novo/", views.novo_processo, name="novo_processo"),
    path("processos/<int:pk>/", views.detalhe_processo, name="detalhe_processo"),
    path("processos/<int:pk>/solicitacao-cotacao.pdf", views.pdf_solicitacao_cotacao, name="pdf_solicitacao_cotacao"),
    path("processos/<int:pk>/necessidades/incluir/", views.acao_incluir_necessidade, name="incluir_necessidade"),
    path("processos/<int:pk>/solicitacoes/enviar/", views.acao_enviar_solicitacao_fornecedor, name="enviar_solicitacao_fornecedor"),
    path("processos/<int:pk>/solicitacoes/<int:solicitacao_id>/enviada/", views.acao_marcar_solicitacao_enviada, name="marcar_solicitacao_enviada"),
    path("processos/<int:pk>/cotacoes/incluir/", views.acao_incluir_cotacao, name="incluir_cotacao"),
    path("processos/<int:pk>/cotacoes/item/incluir/", views.acao_incluir_item_cotacao, name="incluir_item_cotacao"),
    path("processos/<int:pk>/propostas/salvar/", views.acao_salvar_proposta_completa, name="salvar_proposta_completa"),
    path("processos/<int:pk>/cotacoes/<int:cotacao_id>/excluir/", views.acao_excluir_cotacao, name="excluir_cotacao"),
    path("processos/<int:pk>/cotacoes/<int:cotacao_id>/enviar-compatibilizacao/", views.acao_enviar_cotacao_compatibilizacao, name="enviar_cotacao_compatibilizacao"),
    path("processos/<int:pk>/cotacoes/<int:cotacao_id>/enviar-aprovacao/", views.acao_enviar_cotacao_aprovacao, name="enviar_cotacao_aprovacao"),
    path("processos/<int:pk>/cotacoes/<int:cotacao_id>/devolver-negociacao/", views.acao_devolver_cotacao_negociacao, name="devolver_cotacao_negociacao"),
    path("processos/<int:pk>/retornar-etapa/", views.acao_retornar_etapa, name="retornar_etapa"),
    path("processos/<int:pk>/analise-tecnica/salvar/", views.acao_analise_tecnica_lote, name="analise_tecnica_lote"),
    path("processos/<int:pk>/compatibilizacao/aprovar-todos/", views.acao_aprovar_toda_compatibilizacao, name="aprovar_toda_compatibilizacao"),
    path("processos/<int:pk>/decisao-comercial/salvar/", views.acao_decisao_comercial_lote, name="decisao_comercial_lote"),
    path("processos/<int:pk>/compatibilizacao/registrar/", views.acao_compatibilizar, name="compatibilizar"),
    path("processos/<int:pk>/compatibilizacao/concluir/", views.acao_concluir_compatibilizacao, name="concluir_compatibilizacao"),
    path("processos/<int:pk>/negociacao/registrar/", views.acao_negociar, name="negociar"),
    path("processos/<int:pk>/adjudicacao/registrar/", views.acao_adjudicar, name="adjudicar"),
    path("processos/<int:pk>/adjudicacoes/<int:adjudicacao_id>/cancelar/", views.acao_cancelar_adjudicacao, name="cancelar_adjudicacao"),
    path("processos/<int:pk>/negociacao/concluir/", views.acao_concluir_negociacao, name="concluir_negociacao"),
    path("processos/<int:pk>/aprovacao/decidir/", views.acao_aprovar, name="aprovar"),
    path("processos/<int:pk>/documentos/anexar/", views.acao_anexar_documento, name="anexar_documento"),
    path("processos/<int:pk>/pedidos/gerar/", views.acao_gerar_pedidos, name="gerar_pedidos"),
    path("pedidos/", views.lista_pedidos, name="lista_pedidos"),
    path("pedidos/<int:pedido_id>/pdf/", views.pdf_pedido_compra, name="pdf_pedido_compra"),
    path("pedidos/<int:pedido_id>/anexos/", views.acao_anexar_arquivo_pedido, name="anexar_arquivo_pedido"),
    path("pedidos/<int:pedido_id>/status/", views.acao_atualizar_status_pedido, name="atualizar_status_pedido"),
    path("pedidos/<int:pedido_id>/previsao/", views.acao_atualizar_previsao_pedido, name="atualizar_previsao_pedido"),
    path("pedidos/<int:pedido_id>/receber/", views.acao_receber_pedido, name="receber_pedido"),
    path("pedidos/<int:pedido_id>/cancelar/", views.acao_cancelar_pedido, name="cancelar_pedido"),
]
