from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("obras", "0001_initial"),
        ("cadastros", "0003_remover_atividade_subatividade_material"),
        ("compras", "0019_suprimentoreferencia_multivinculo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenciaFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(max_length=30)),
                ("ano", models.PositiveIntegerField()),
                ("ultimo_numero", models.PositiveIntegerField(default=0)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("tipo", "ano"), name="fin_seq_tipo_ano_uniq")]},
        ),
        migrations.CreateModel(
            name="PlanoFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(db_index=True, max_length=30, unique=True)),
                ("nome", models.CharField(db_index=True, max_length=160)),
                ("tipo", models.CharField(choices=[("DESPESA", "Despesa"), ("RECEITA", "Receita")], default="DESPESA", max_length=20)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("pai", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="filhos", to="financeiro.planofinanceiro")),
            ],
            options={"verbose_name": "Conta do plano financeiro", "verbose_name_plural": "Plano financeiro", "ordering": ("codigo", "nome")},
        ),
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=120)),
                ("banco", models.CharField(max_length=120)),
                ("agencia", models.CharField(blank=True, max_length=30)),
                ("conta", models.CharField(blank=True, max_length=40)),
                ("empresa", models.CharField(blank=True, max_length=160)),
                ("saldo_inicial", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("data_saldo_inicial", models.DateField(blank=True, null=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Conta bancária", "verbose_name_plural": "Contas bancárias", "ordering": ("descricao", "banco")},
        ),
        migrations.CreateModel(
            name="AlcadaAprovacaoFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=140)),
                ("valor_minimo", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="A partir deste valor, este nível passa a ser obrigatório.", max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("cargo", models.CharField(blank=True, max_length=30)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("obra", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="alcadas_financeiras", to="obras.obra")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alcadas_financeiras", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Alçada financeira", "verbose_name_plural": "Alçadas financeiras", "ordering": ("ordem", "valor_minimo", "id")},
        ),
        migrations.CreateModel(
            name="DespesaRecorrente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=220)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("dia_vencimento", models.PositiveSmallIntegerField(default=10)),
                ("inicio", models.DateField()),
                ("fim", models.DateField(blank=True, null=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="despesas_recorrentes_criadas", to=settings.AUTH_USER_MODEL)),
                ("fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="despesas_recorrentes", to="cadastros.fornecedor")),
                ("obra", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="despesas_recorrentes", to="obras.obra")),
                ("plano_financeiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="despesas_recorrentes", to="financeiro.planofinanceiro")),
            ],
            options={"verbose_name": "Despesa recorrente", "verbose_name_plural": "Despesas recorrentes", "ordering": ("descricao",)},
        ),
        migrations.CreateModel(
            name="PrevisaoFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origem", models.CharField(choices=[("COMPRA", "Compra"), ("CONTRATO", "Contrato"), ("MEDICAO", "Medição"), ("RECORRENTE", "Despesa recorrente"), ("MANUAL", "Manual")], db_index=True, default="MANUAL", max_length=20)),
                ("certeza", models.CharField(choices=[("COMPROMETIDO", "Comprometido"), ("CONTRATADO", "Contratado"), ("PREVISTO", "Previsto")], db_index=True, default="PREVISTO", max_length=20)),
                ("descricao", models.CharField(max_length=300)),
                ("competencia", models.DateField(blank=True, null=True)),
                ("data_prevista", models.DateField(blank=True, db_index=True, null=True)),
                ("valor_previsto", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("ativa", models.BooleanField(db_index=True, default=True)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="previsoes_financeiras_criadas", to=settings.AUTH_USER_MODEL)),
                ("despesa_recorrente", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="previsoes", to="financeiro.despesarecorrente")),
                ("fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="previsoes_financeiras", to="cadastros.fornecedor")),
                ("obra", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="previsoes_financeiras", to="obras.obra")),
                ("parcela_pedido", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="previsao_financeira", to="compras.parcelaprevistapedido")),
                ("pedido", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="previsoes_financeiras", to="compras.pedidocompra")),
                ("plano_financeiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="previsoes", to="financeiro.planofinanceiro")),
            ],
            options={"ordering": ("data_prevista", "id")},
        ),
        migrations.AddIndex(model_name="previsaofinanceira", index=models.Index(fields=["ativa", "data_prevista"], name="fin_prev_ativa_data_idx")),
        migrations.AddIndex(model_name="previsaofinanceira", index=models.Index(fields=["obra", "origem"], name="fin_prev_obra_orig_idx")),
        migrations.CreateModel(
            name="TituloPagar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(db_index=True, max_length=24, unique=True)),
                ("origem", models.CharField(choices=[("COMPRA", "Compra"), ("CONTRATO", "Contrato"), ("MEDICAO", "Medição"), ("DESPESA", "Despesa"), ("IMPOSTO", "Imposto"), ("ADIANTAMENTO", "Adiantamento"), ("REEMBOLSO", "Reembolso"), ("FOLHA", "Folha"), ("OUTRO", "Outro")], db_index=True, default="OUTRO", max_length=20)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("DOCUMENTO_RECEBIDO", "Documento recebido"), ("EM_CONFERENCIA", "Em conferência"), ("AGUARDANDO_APROVACAO", "Aguardando aprovação"), ("APROVADO", "Aprovado"), ("PROGRAMADO", "Programado"), ("PAGO_PARCIAL", "Pago parcialmente"), ("PAGO", "Pago"), ("BLOQUEADO", "Bloqueado"), ("REJEITADO", "Rejeitado"), ("CANCELADO", "Cancelado")], db_index=True, default="RASCUNHO", max_length=30)),
                ("conferencia", models.CharField(choices=[("NAO_CONFERIDO", "Não conferido"), ("CONFERIDO", "Conferido"), ("DIVERGENCIA", "Divergência")], db_index=True, default="NAO_CONFERIDO", max_length=20)),
                ("descricao", models.CharField(max_length=300)),
                ("documento_numero", models.CharField(blank=True, db_index=True, max_length=100)),
                ("arquivo_documento", models.FileField(blank=True, upload_to="financeiro/documentos/%Y/%m/")),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("competencia", models.DateField(blank=True, null=True)),
                ("vencimento", models.DateField(blank=True, db_index=True, null=True)),
                ("valor_original", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("desconto", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("juros", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("multa", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("outros_acrescimos", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("observacao", models.TextField(blank=True)),
                ("ciclo_aprovacao", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="titulos_financeiros_criados", to=settings.AUTH_USER_MODEL)),
                ("fornecedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="titulos_financeiros", to="cadastros.fornecedor")),
                ("obra", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="titulos_financeiros", to="obras.obra")),
                ("pedido", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="titulos_financeiros", to="compras.pedidocompra")),
                ("plano_financeiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="titulos", to="financeiro.planofinanceiro")),
                ("previsao_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="titulos_gerados", to="financeiro.previsaofinanceira")),
                ("recebimento", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="titulo_financeiro", to="compras.recebimentopedido")),
            ],
            options={"ordering": ("vencimento", "numero")},
        ),
        migrations.AddIndex(model_name="titulopagar", index=models.Index(fields=["status", "vencimento"], name="fin_tit_st_venc_idx")),
        migrations.AddIndex(model_name="titulopagar", index=models.Index(fields=["obra", "status"], name="fin_tit_obra_st_idx")),
        migrations.AddIndex(model_name="titulopagar", index=models.Index(fields=["fornecedor", "vencimento"], name="fin_tit_forn_venc_idx")),
        migrations.CreateModel(
            name="HistoricoTituloFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evento", models.CharField(max_length=80)),
                ("descricao", models.CharField(max_length=500)),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("titulo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historico", to="financeiro.titulopagar")),
                ("usuario", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historicos_titulos_financeiros", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.CreateModel(
            name="AprovacaoTituloFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ciclo", models.PositiveIntegerField(default=1)),
                ("decisao", models.CharField(choices=[("APROVADO", "Aprovado"), ("REJEITADO", "Rejeitado")], max_length=20)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("alcada", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decisoes", to="financeiro.alcadaaprovacaofinanceira")),
                ("titulo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="aprovacoes", to="financeiro.titulopagar")),
                ("usuario", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="aprovacoes_financeiras", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("criado_em", "id")},
        ),
        migrations.AddConstraint(model_name="aprovacaotitulofinanceiro", constraint=models.UniqueConstraint(fields=("titulo", "ciclo", "alcada"), name="fin_aprov_tit_ciclo_alc_uniq")),
        migrations.CreateModel(
            name="LotePagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(db_index=True, max_length=24, unique=True)),
                ("data_programada", models.DateField(db_index=True)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("PRONTO", "Pronto para pagamento"), ("EXECUTADO", "Executado"), ("CANCELADO", "Cancelado")], db_index=True, default="RASCUNHO", max_length=20)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("conta_bancaria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_pagamento", to="financeiro.contabancaria")),
                ("criado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lotes_financeiros_criados", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-data_programada", "-id")},
        ),
        migrations.CreateModel(
            name="ItemLotePagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor_programado", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="financeiro.lotepagamento")),
                ("titulo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programacoes", to="financeiro.titulopagar")),
            ],
        ),
        migrations.AddConstraint(model_name="itemlotepagamento", constraint=models.UniqueConstraint(fields=("lote", "titulo"), name="fin_lote_titulo_uniq")),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_pagamento", models.DateField(db_index=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("forma", models.CharField(choices=[("PIX", "PIX"), ("TED", "TED"), ("BOLETO", "Boleto"), ("TRANSFERENCIA", "Transferência"), ("DEBITO", "Débito"), ("CHEQUE", "Cheque"), ("DINHEIRO", "Dinheiro"), ("OUTRO", "Outro")], default="PIX", max_length=20)),
                ("referencia_bancaria", models.CharField(blank=True, max_length=120)),
                ("comprovante", models.FileField(blank=True, upload_to="financeiro/comprovantes/%Y/%m/")),
                ("observacao", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("EFETIVADO", "Efetivado"), ("ESTORNADO", "Estornado")], db_index=True, default="EFETIVADO", max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("estornado_em", models.DateTimeField(blank=True, null=True)),
                ("conta_bancaria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pagamentos", to="financeiro.contabancaria")),
                ("estornado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pagamentos_financeiros_estornados", to=settings.AUTH_USER_MODEL)),
                ("lote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pagamentos", to="financeiro.lotepagamento")),
                ("registrado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pagamentos_financeiros_registrados", to=settings.AUTH_USER_MODEL)),
                ("titulo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pagamentos", to="financeiro.titulopagar")),
                ("motivo_estorno", models.TextField(blank=True)),
            ],
            options={"ordering": ("-data_pagamento", "-id")},
        ),
        migrations.AddIndex(model_name="pagamento", index=models.Index(fields=["conta_bancaria", "data_pagamento"], name="fin_pag_conta_data_idx")),
        migrations.CreateModel(
            name="MovimentacaoBancaria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("CREDITO", "Crédito"), ("DEBITO", "Débito"), ("AJUSTE_CREDITO", "Ajuste de crédito"), ("AJUSTE_DEBITO", "Ajuste de débito")], db_index=True, max_length=20)),
                ("data", models.DateField(db_index=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("descricao", models.CharField(max_length=300)),
                ("conciliado", models.BooleanField(db_index=True, default=False)),
                ("referencia_extrato", models.CharField(blank=True, max_length=160)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("conta_bancaria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes", to="financeiro.contabancaria")),
                ("criado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movimentacoes_bancarias_criadas", to=settings.AUTH_USER_MODEL)),
                ("pagamento", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacao_bancaria", to="financeiro.pagamento")),
            ],
            options={"ordering": ("-data", "-id")},
        ),
        migrations.AddIndex(model_name="movimentacaobancaria", index=models.Index(fields=["conta_bancaria", "data"], name="fin_mov_conta_data_idx")),
    ]
