# Generated by Django 6.0.7 on 2026-07-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('tipo_arquivo', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel XLSX'), ('XLS', 'Excel XLS'), ('GOOGLE_SHEETS', 'Google Sheets'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo do arquivo')),
                ('google_drive_file_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID do arquivo no Google Drive')),
                ('mime_type', models.CharField(blank=True, max_length=150, verbose_name='MIME type')),
                ('caminho_temporario', models.CharField(blank=True, max_length=500, verbose_name='Caminho temporário')),
                ('tamanho_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Tamanho em bytes')),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Hash do arquivo')),
                ('data_modificacao_drive', models.DateTimeField(blank=True, null=True, verbose_name='Modificado no Drive em')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de referência')),
                ('aba', models.CharField(blank=True, max_length=150, verbose_name='Aba')),
                ('total_linhas', models.PositiveBigIntegerField(default=0, verbose_name='Total de linhas')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Arquivo importado',
                'verbose_name_plural': 'Arquivos importados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRONOGRAMA_OBRA', 'Cronograma de obra'), ('CRONOGRAMA_SUPRIMENTOS', 'Cronograma de suprimentos'), ('OUTRO', 'Outro')], max_length=40, verbose_name='Tipo')),
                ('origem', models.CharField(choices=[('GOOGLE_DRIVE', 'Google Drive'), ('UPLOAD_MANUAL', 'Upload manual'), ('DIRETORIO_LOCAL', 'Diretório local')], default='GOOGLE_DRIVE', max_length=30, verbose_name='Origem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDA', 'Concluída'), ('CONCLUIDA_COM_ERROS', 'Concluída com erros'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=30, verbose_name='Status')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('total_linhas', models.PositiveBigIntegerField(default=0, verbose_name='Total de linhas')),
                ('total_processadas', models.PositiveBigIntegerField(default=0, verbose_name='Linhas processadas')),
                ('total_inseridas', models.PositiveBigIntegerField(default=0, verbose_name='Linhas inseridas')),
                ('total_atualizadas', models.PositiveBigIntegerField(default=0, verbose_name='Linhas atualizadas')),
                ('total_ignoradas', models.PositiveBigIntegerField(default=0, verbose_name='Linhas ignoradas')),
                ('total_erros', models.PositiveBigIntegerField(default=0, verbose_name='Total de erros')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('executada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Executada por')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ErroImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('AVISO', 'Aviso'), ('ERRO', 'Erro'), ('CRITICO', 'Crítico')], default='ERRO', max_length=20, verbose_name='Nível')),
                ('linha', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Linha')),
                ('coluna', models.CharField(blank=True, max_length=150, verbose_name='Coluna')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('valor_original', models.TextField(blank=True, verbose_name='Valor original')),
                ('dados_linha', models.JSONField(blank=True, default=dict, verbose_name='Dados da linha')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros', to='integracoes.arquivoimportado', verbose_name='Arquivo')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='integracoes.importacao', verbose_name='Importação')),
            ],
            options={
                'verbose_name': 'Erro de importação',
                'verbose_name_plural': 'Erros de importação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='arquivoimportado',
            name='importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='integracoes.importacao', verbose_name='Importação'),
        ),
        migrations.AddIndex(
            model_name='importacao',
            index=models.Index(fields=['tipo', 'status'], name='integracao_tipo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importacao',
            index=models.Index(fields=['criado_em'], name='integracao_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='erroimportacao',
            index=models.Index(fields=['importacao', 'nivel'], name='erro_importacao_nivel_idx'),
        ),
        migrations.AddIndex(
            model_name='erroimportacao',
            index=models.Index(fields=['arquivo', 'linha'], name='erro_arquivo_linha_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivoimportado',
            index=models.Index(fields=['google_drive_file_id', 'data_modificacao_drive'], name='arquivo_drive_modificacao_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivoimportado',
            index=models.Index(fields=['hash_arquivo'], name='arquivo_hash_idx'),
        ),
    ]
