# Generated by Django 6.0.7 on 2026-07-21 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da obra')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Código')),
                ('nome_curto', models.CharField(blank=True, max_length=120, verbose_name='Nome curto')),
                ('tipo_obra', models.CharField(choices=[('CASA', 'Casa'), ('PREDIO', 'Prédio'), ('CONDOMINIO', 'Condomínio'), ('COMERCIAL', 'Comercial'), ('OUTRO', 'Outro')], default='CASA', max_length=20, verbose_name='Tipo de obra')),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('EM_ANDAMENTO', 'Em andamento'), ('PARALISADA', 'Paralisada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJAMENTO', max_length=30, verbose_name='Status')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('area_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área do terreno')),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área construída')),
                ('quantidade_unidades', models.PositiveIntegerField(default=1, verbose_name='Quantidade de unidades')),
                ('data_inicio_prevista', models.DateField(blank=True, null=True, verbose_name='Início previsto')),
                ('data_termino_prevista', models.DateField(blank=True, null=True, verbose_name='Término previsto')),
                ('data_inicio_real', models.DateField(blank=True, null=True, verbose_name='Início real')),
                ('data_termino_real', models.DateField(blank=True, null=True, verbose_name='Término real')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('codigo', models.CharField(blank=True, max_length=60, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('TECNICO', 'Técnico'), ('COMUM', 'Área comum'), ('OUTRO', 'Outro')], default='INTERNO', max_length=20, verbose_name='Tipo')),
                ('pavimento', models.CharField(blank=True, max_length=80, verbose_name='Pavimento')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['obra', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('BLOCO', 'Bloco'), ('TORRE', 'Torre'), ('SETOR', 'Setor'), ('OUTRO', 'Outro')], default='CASA', max_length=20, verbose_name='Tipo')),
                ('bloco', models.CharField(blank=True, max_length=80, verbose_name='Bloco')),
                ('pavimento', models.CharField(blank=True, max_length=80, verbose_name='Pavimento')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['obra', 'ordem', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['codigo'], name='obras_obra_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['status', 'ativa'], name='obras_obra_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ambiente',
            index=models.Index(fields=['obra', 'ativo'], name='obras_ambiente_obra_idx'),
        ),
        migrations.AddIndex(
            model_name='ambiente',
            index=models.Index(fields=['obra', 'tipo'], name='obras_ambiente_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='ambiente',
            constraint=models.UniqueConstraint(fields=('obra', 'nome'), name='obras_ambiente_obra_nome_uniq'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['obra', 'ativa'], name='obras_unidade_obra_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['obra', 'tipo'], name='obras_unidade_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(fields=('obra', 'codigo'), name='obras_unidade_obra_codigo_uniq'),
        ),
    ]
