# Generated by Django 6.0.7 on 2026-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_ficha_tecnica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichatecnicaobra',
            options={'ordering': ('obra__nome',), 'verbose_name': 'Ficha técnica da obra', 'verbose_name_plural': 'Fichas técnicas das obras'},
        ),
    ]
