# Generated by Django 6.0.7 on 2026-08-11 18:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('planejamento', '0009_itemcronogramasuprimento_datas_realizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_proposta', models.DateField(blank=True, null=True)),
                ('prazo_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=255)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='compras/cotacoes/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_fornecedor_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CotacaoFornecedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_comercial', models.CharField(blank=True, max_length=500)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('especificacao_ofertada', models.TextField(blank=True)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('valor_unitario_cotado', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('desconto_cotado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacoes', models.TextField(blank=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacaofornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompatibilizacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('APROVADO_COM_RESSALVA', 'Aprovado com ressalva'), ('REPROVADO', 'Reprovado')], max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('ressalva_motivo', models.TextField(blank=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compatibilizacoes_compras', to=settings.AUTH_USER_MODEL)),
                ('item_cotado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibilizacoes', to='compras.cotacaofornecedoritem')),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('documento',), name='comp_fornec_doc_uniq')],
            },
        ),
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to='compras.fornecedorcompra'),
        ),
        migrations.CreateModel(
            name='NecessidadeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade_necessaria', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantidade_incluida', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('observacao', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('ATIVA', 'Ativa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], db_index=True, default='ATIVA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necessidades_compra', to='planejamento.atividadeplanejamento')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necessidades_compra', to='planejamento.insumoplanejamento')),
                ('suprimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necessidades_compra', to='planejamento.suprimentoatividade')),
            ],
        ),
        migrations.AddField(
            model_name='cotacaofornecedoritem',
            name='necessidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotados', to='compras.necessidadecompra'),
        ),
        migrations.CreateModel(
            name='NegociacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario_negociado', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('frete_negociado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prazo_entrega_dias_negociado', models.PositiveIntegerField(blank=True, null=True)),
                ('condicao_pagamento_negociada', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negociacoes_compras', to=settings.AUTH_USER_MODEL)),
                ('item_cotado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negociacao', to='compras.cotacaofornecedoritem')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEDIDO_EMITIDO', 'Pedido emitido'), ('CONFIRMADO', 'Confirmado'), ('EM_PRODUCAO', 'Em produção'), ('PRONTO_EXPEDICAO', 'Pronto para expedição'), ('EM_TRANSPORTE', 'Em transporte'), ('ENTREGA_PARCIAL', 'Entrega parcial'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='PEDIDO_EMITIDO', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('descontos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=255)),
                ('previsao_entrega_original', models.DateField(blank=True, null=True)),
                ('previsao_entrega_atual', models.DateField(blank=True, null=True)),
                ('local_entrega', models.CharField(blank=True, max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_cancelados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='compras.fornecedorcompra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='obras.obra')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaPrevistaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('evento_gatilho', models.CharField(choices=[('DATA', 'Data'), ('ASSINATURA', 'Assinatura'), ('FABRICACAO', 'Fabricação'), ('ENTREGA', 'Entrega'), ('INSTALACAO', 'Instalação'), ('OUTRO', 'Outro')], default='DATA', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_previstas', to='compras.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPrevisaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsao_anterior', models.DateField(blank=True, null=True)),
                ('previsao_nova', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_previsao_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_previsoes', to='compras.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='planejamento.insumoplanejamento')),
                ('necessidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='compras.necessidadecompra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='compras.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('etapa_atual', models.CharField(choices=[('COTACAO', 'Cotação'), ('COMPATIBILIZACAO', 'Compatibilização'), ('NEGOCIACAO', 'Negociação'), ('APROVACAO', 'Aprovação'), ('CONTRATACAO', 'Contratação'), ('CONTRATADO', 'Contratado')], db_index=True, default='COTACAO', max_length=30)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_COTACAO', 'Aguardando cotação'), ('EM_COTACAO', 'Em cotação'), ('AGUARDANDO_COMPATIBILIZACAO', 'Aguardando compatibilização'), ('EM_COMPATIBILIZACAO', 'Em compatibilização'), ('EM_NEGOCIACAO', 'Em negociação'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('AJUSTE_SOLICITADO', 'Ajuste solicitado'), ('APROVADO', 'Aprovado'), ('EM_CONTRATACAO', 'Em contratação'), ('CONTRATADO', 'Contratado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RASCUNHO', max_length=40)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_cotacao_concluida', models.DateTimeField(blank=True, null=True)),
                ('data_compatibilizacao_concluida', models.DateTimeField(blank=True, null=True)),
                ('data_negociacao_concluida', models.DateTimeField(blank=True, null=True)),
                ('data_contratacao_concluida', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_compra_cancelados', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_compra_responsavel', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('item_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_compra', to='planejamento.itemcronogramasuprimento')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_compra', to='obras.obra')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='compras.processocompra'),
        ),
        migrations.AddField(
            model_name='necessidadecompra',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='compras.processocompra'),
        ),
        migrations.CreateModel(
            name='HistoricoProcessoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_compras', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='compras.processocompra')),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.AddField(
            model_name='cotacaofornecedor',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='compras.processocompra'),
        ),
        migrations.CreateModel(
            name='AprovacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.PositiveIntegerField(default=1)),
                ('decisao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('AJUSTE_SOLICITADO', 'Ajuste solicitado')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_compras', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes', to='compras.processocompra')),
            ],
        ),
        migrations.CreateModel(
            name='AdjudicacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('valor_unitario_final', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('prazo_entrega_dias_final', models.PositiveIntegerField(blank=True, null=True)),
                ('condicao_pagamento_final', models.CharField(blank=True, max_length=255)),
                ('selecionado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelada', models.BooleanField(db_index=True, default=False)),
                ('selecionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudicacoes_compras', to=settings.AUTH_USER_MODEL)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjudicacoes', to='compras.cotacaofornecedor')),
                ('item_cotado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjudicacoes', to='compras.cotacaofornecedoritem')),
                ('necessidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjudicacoes', to='compras.necessidadecompra')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjudicacoes', to='compras.processocompra')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoCompraAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_compras', to='planejamento.atividadeplanejamento')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_compra_atividade_criados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_atividades', to='compras.processocompra')),
            ],
        ),
        migrations.CreateModel(
            name='SequenciaDocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('ano', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'ano'), name='comp_seq_tipo_ano_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='processocompra',
            index=models.Index(fields=['obra', 'status'], name='comp_proc_obra_st_idx'),
        ),
        migrations.AddIndex(
            model_name='processocompra',
            index=models.Index(fields=['comprador', 'etapa_atual'], name='comp_proc_comp_et_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotacaofornecedor',
            constraint=models.UniqueConstraint(fields=('processo', 'fornecedor'), name='comp_cot_proc_forn_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processocompraatividade',
            constraint=models.UniqueConstraint(fields=('processo', 'atividade'), name='comp_proc_atv_uniq'),
        ),
    ]
