# Generated by Django 6.0.7 on 2026-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_recebimento_nota_fiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoprevisaopedido',
            options={'ordering': ('-criado_em', '-id')},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AlterField(
            model_name='processocompra',
            name='etapa_atual',
            field=models.CharField(choices=[('COTACAO', 'Cotação'), ('COMPATIBILIZACAO', 'Análise técnica'), ('NEGOCIACAO', 'Negociação'), ('APROVACAO', 'Aprovação'), ('CONTRATACAO', 'Contratação'), ('CONTRATADO', 'Contratado')], db_index=True, default='COTACAO', max_length=30),
        ),
    ]
