from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import core.storage


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0035_apropriacao_e_forma_pagamento_gf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(db_index=True, max_length=24, unique=True)),
                ("contratado_razao_social", models.CharField(max_length=255)),
                ("contratado_cnpj", models.CharField(blank=True, max_length=32)),
                ("contratado_endereco", models.CharField(blank=True, max_length=500)),
                ("contratado_email", models.EmailField(blank=True, max_length=254)),
                ("representante_nome", models.CharField(blank=True, max_length=255)),
                ("representante_nacionalidade", models.CharField(blank=True, default="brasileiro(a)", max_length=80)),
                ("representante_estado_civil", models.CharField(blank=True, max_length=80)),
                ("representante_profissao", models.CharField(blank=True, max_length=120)),
                ("representante_cpf", models.CharField(blank=True, max_length=32)),
                ("representante_endereco", models.CharField(blank=True, max_length=500)),
                ("modalidade_fornecimento", models.CharField(default="somente com o fornecimento de mão-de-obra", max_length=255)),
                ("objeto_contrato", models.TextField()),
                ("area_obra", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("descricao_ambientes_objeto", models.TextField(blank=True)),
                ("escritorio_arquitetura", models.CharField(blank=True, max_length=255)),
                ("responsavel_supervisao", models.CharField(blank=True, max_length=255)),
                ("prazo_execucao", models.CharField(max_length=120)),
                ("multa_atraso", models.DecimalField(decimal_places=2, default=1500, max_digits=14)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("favorecido_nome", models.CharField(blank=True, max_length=255)),
                ("favorecido_documento_tipo", models.CharField(blank=True, default="CNPJ", max_length=10)),
                ("favorecido_documento", models.CharField(blank=True, max_length=32)),
                ("banco", models.CharField(blank=True, max_length=120)),
                ("agencia", models.CharField(blank=True, max_length=50)),
                ("conta", models.CharField(blank=True, max_length=80)),
                ("operacao", models.CharField(blank=True, max_length=50)),
                ("pix", models.CharField(blank=True, max_length=255)),
                ("avalista_1_nome", models.CharField(blank=True, max_length=255)),
                ("avalista_1_cpf", models.CharField(blank=True, max_length=32)),
                ("avalista_2_nome", models.CharField(blank=True, max_length=255)),
                ("avalista_2_cpf", models.CharField(blank=True, max_length=32)),
                ("cidade_assinatura", models.CharField(default="Brasília", max_length=120)),
                ("data_contrato", models.DateField()),
                ("observacoes_internas", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("AGUARDANDO_APROVACAO", "Aguardando aprovação"), ("DEVOLVIDO", "Devolvido para correção"), ("REPROVADO", "Reprovado"), ("APROVADO", "Aprovado"), ("AGUARDANDO_ASSINATURA", "Aguardando assinatura"), ("ASSINADO", "Assinado")], db_index=True, default="RASCUNHO", max_length=32)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("enviado_aprovacao_em", models.DateTimeField(blank=True, null=True)),
                ("decidido_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_decisao", models.TextField(blank=True)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255)),
                ("google_doc_id", models.CharField(blank=True, max_length=255)),
                ("google_doc_url", models.URLField(blank=True, max_length=1000)),
                ("drive_assinado_id", models.CharField(blank=True, max_length=255)),
                ("drive_assinado_url", models.URLField(blank=True, max_length=1000)),
                ("arquivo_docx", models.FileField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to="compras/contratos/gerados/%Y/%m/")),
                ("arquivo_assinado", models.FileField(blank=True, storage=core.storage.PrivateMediaStorage(), upload_to="compras/contratos/assinados/%Y/%m/")),
                ("aprovado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contratos_compra_aprovados", to=settings.AUTH_USER_MODEL)),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_compra_criados", to=settings.AUTH_USER_MODEL)),
                ("fornecedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_compra", to="cadastros.fornecedor")),
                ("obra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_compra", to="obras.obra")),
                ("processo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contratos", to="compras.processocompra")),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.CreateModel(
            name="HistoricoContratoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evento", models.CharField(max_length=60)),
                ("descricao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("contrato", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historico", to="compras.contratocompra")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historicos_contratos_compra", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.AddIndex(model_name="contratocompra", index=models.Index(fields=["status", "criado_em"], name="comp_cont_status_idx")),
        migrations.AddIndex(model_name="contratocompra", index=models.Index(fields=["obra", "status"], name="comp_cont_obra_idx")),
        migrations.AddIndex(model_name="contratocompra", index=models.Index(fields=["fornecedor", "status"], name="comp_cont_forn_idx")),
    ]
